// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-aggregates.ts

export const entities: any[] = []
export const relations: any[] = []
export const interactions: any[] = []
export const activities: any[] = []
export const dicts: any[] = []
