/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/interaction/ViewUserChannels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query ViewUserChannels
         * @description Query interaction: ViewUserChannels
         */
        post: operations["ViewUserChannels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/ViewChannelFeedStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query ViewChannelFeedStream
         * @description Query interaction: ViewChannelFeedStream
         */
        post: operations["ViewChannelFeedStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/ViewChannelMediaContent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query ViewChannelMediaContent
         * @description Query interaction: ViewChannelMediaContent
         */
        post: operations["ViewChannelMediaContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/ViewChannelDetails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query ViewChannelDetails
         * @description Query interaction: ViewChannelDetails
         */
        post: operations["ViewChannelDetails"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/ViewNanobanana2ImageGenerationStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query ViewNanobanana2ImageGenerationStatus
         * @description Query interaction: ViewNanobanana2ImageGenerationStatus
         */
        post: operations["ViewNanobanana2ImageGenerationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/ViewSora2VideoGenerationStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query ViewSora2VideoGenerationStatus
         * @description Query interaction: ViewSora2VideoGenerationStatus
         */
        post: operations["ViewSora2VideoGenerationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/CreateChannel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute CreateChannel
         * @description Mutation interaction: CreateChannel
         */
        post: operations["CreateChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/UpdateChannel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute UpdateChannel
         * @description Mutation interaction: UpdateChannel
         */
        post: operations["UpdateChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/DeleteChannel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute DeleteChannel
         * @description Mutation interaction: DeleteChannel
         */
        post: operations["DeleteChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/AddMediaToFeedStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute AddMediaToFeedStream
         * @description Mutation interaction: AddMediaToFeedStream
         */
        post: operations["AddMediaToFeedStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/RemoveMediaFromFeedStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute RemoveMediaFromFeedStream
         * @description Mutation interaction: RemoveMediaFromFeedStream
         */
        post: operations["RemoveMediaFromFeedStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/ReorderFeedStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute ReorderFeedStream
         * @description Mutation interaction: ReorderFeedStream
         */
        post: operations["ReorderFeedStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/UploadMediaToChannel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute UploadMediaToChannel
         * @description Mutation interaction: UploadMediaToChannel
         */
        post: operations["UploadMediaToChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/DeleteMediaContent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute DeleteMediaContent
         * @description Mutation interaction: DeleteMediaContent
         */
        post: operations["DeleteMediaContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/GenerateImageFromUploadedImage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute GenerateImageFromUploadedImage
         * @description Mutation interaction: GenerateImageFromUploadedImage
         */
        post: operations["GenerateImageFromUploadedImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/GenerateVideoFromPrompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute GenerateVideoFromPrompt
         * @description Mutation interaction: GenerateVideoFromPrompt
         */
        post: operations["GenerateVideoFromPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/RetryNanobanana2ImageGeneration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute RetryNanobanana2ImageGeneration
         * @description Mutation interaction: RetryNanobanana2ImageGeneration
         */
        post: operations["RetryNanobanana2ImageGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interaction/RetrySora2VideoGeneration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute RetrySora2VideoGeneration
         * @description Mutation interaction: RetrySora2VideoGeneration
         */
        post: operations["RetrySora2VideoGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call register API
         * @description Custom API endpoint: register
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call login API
         * @description Custom API endpoint: login
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom/getUploadUrl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call getUploadUrl API
         * @description Custom API endpoint: getUploadUrl
         */
        post: operations["getUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom/queryNanobanana2ImageGenerationStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call queryNanobanana2ImageGenerationStatus API
         * @description Custom API endpoint: queryNanobanana2ImageGenerationStatus
         */
        post: operations["queryNanobanana2ImageGenerationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom/querySora2VideoGenerationStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call querySora2VideoGenerationStatus API
         * @description Custom API endpoint: querySora2VideoGenerationStatus
         */
        post: operations["querySora2VideoGenerationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Recursive attribute query data for querying related entities. Can be a string (attribute name) or a tuple [relationName, { attributeQuery?: AttributeQueryData }] */
        AttributeQueryData: components["schemas"]["AttributeQueryItem"][];
        /** @description Single item in AttributeQueryData - either an attribute name or a relation query tuple */
        AttributeQueryItem: string | components["schemas"]["RelationQueryTuple"];
        /** @description Tuple format for querying related entities: [relationName, { attributeQuery?: AttributeQueryData }] */
        RelationQueryTuple: unknown[];
        /** @description Options for relation query containing nested attributeQuery */
        RelationQueryOptions: {
            attributeQuery?: components["schemas"]["AttributeQueryData"];
        };
        /** @description Match expression for filtering records */
        MatchExpression: {
            /** @description The field key to match (e.g., "id", "owner.id") */
            key: string;
            /** @description Tuple of [operator, value] (e.g., ["=", "123"]) */
            value: unknown[];
        };
        /** @description Query modifier for pagination and sorting */
        QueryModifier: {
            /** @description Maximum number of records to return */
            limit?: number;
            /** @description Number of records to skip */
            offset?: number;
            /** @description Field ordering (e.g., { "createdAt": "DESC" }) */
            orderBy?: {
                [key: string]: "ASC" | "DESC";
            };
        };
        /** @description Query parameters for query-type interactions */
        UserQueryParams: {
            match?: components["schemas"]["MatchExpression"];
            attributeQuery?: components["schemas"]["AttributeQueryData"];
            modifier?: components["schemas"]["QueryModifier"];
        };
        /** @description Response from query-type interactions */
        QueryResponse: {
            /** @description Array of matching records */
            data: {
                [key: string]: unknown;
            }[];
            /** @description Error information if the query failed */
            error?: Record<string, never> | null;
            /** @description Side effects from the query */
            effects?: Record<string, never> | null;
        };
        /** @description Response from mutation-type interactions */
        MutationResponse: {
            /** @description Result data from the mutation */
            data?: {
                [key: string]: unknown;
            } | null;
            /** @description Error information if the mutation failed */
            error?: Record<string, never> | null;
            /** @description Side effects from the mutation */
            effects?: Record<string, never> | null;
        };
        /** @description Error response */
        ErrorResponse: {
            /** @description Error message */
            error: string;
            /** @description Additional error details */
            details?: string | null;
        };
        /** @description Request body for ViewUserChannels interaction */
        ViewUserChannelsRequest: {
            query?: components["schemas"]["UserQueryParams"];
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Request body for ViewChannelFeedStream interaction */
        ViewChannelFeedStreamRequest: {
            query?: components["schemas"]["UserQueryParams"];
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Request body for ViewChannelMediaContent interaction */
        ViewChannelMediaContentRequest: {
            query?: components["schemas"]["UserQueryParams"];
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Request body for ViewChannelDetails interaction */
        ViewChannelDetailsRequest: {
            query?: components["schemas"]["UserQueryParams"];
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Request body for ViewNanobanana2ImageGenerationStatus interaction */
        ViewNanobanana2ImageGenerationStatusRequest: {
            query?: components["schemas"]["UserQueryParams"];
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Request body for ViewSora2VideoGenerationStatus interaction */
        ViewSora2VideoGenerationStatusRequest: {
            query?: components["schemas"]["UserQueryParams"];
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for CreateChannel interaction */
        CreateChannelPayload: {
            name: string;
            description?: string;
            prompt: string;
            referenceImageUrl: string;
        };
        /** @description Request body for CreateChannel interaction */
        CreateChannelRequest: {
            payload?: {
                name: string;
                description?: string;
                prompt: string;
                referenceImageUrl: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for UpdateChannel interaction */
        UpdateChannelPayload: {
            channelId: string;
            name?: string;
            description?: string;
        };
        /** @description Request body for UpdateChannel interaction */
        UpdateChannelRequest: {
            payload?: {
                channelId: string;
                name?: string;
                description?: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for DeleteChannel interaction */
        DeleteChannelPayload: {
            channelId: string;
        };
        /** @description Request body for DeleteChannel interaction */
        DeleteChannelRequest: {
            payload?: {
                channelId: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for AddMediaToFeedStream interaction */
        AddMediaToFeedStreamPayload: {
            channelId: string;
            mediaContentId: string;
            order?: number;
        };
        /** @description Request body for AddMediaToFeedStream interaction */
        AddMediaToFeedStreamRequest: {
            payload?: {
                channelId: string;
                mediaContentId: string;
                order?: number;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for RemoveMediaFromFeedStream interaction */
        RemoveMediaFromFeedStreamPayload: {
            feedItemId: string;
        };
        /** @description Request body for RemoveMediaFromFeedStream interaction */
        RemoveMediaFromFeedStreamRequest: {
            payload?: {
                feedItemId: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for ReorderFeedStream interaction */
        ReorderFeedStreamPayload: {
            channelId: string;
            /** @description Collection of object */
            feedItemOrders: {
                [key: string]: unknown;
            }[];
        };
        /** @description Request body for ReorderFeedStream interaction */
        ReorderFeedStreamRequest: {
            payload?: {
                channelId: string;
                /** @description Collection of object */
                feedItemOrders: {
                    [key: string]: unknown;
                }[];
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for UploadMediaToChannel interaction */
        UploadMediaToChannelPayload: {
            channelId: string;
            mediaUrl: string;
            fileName: string;
            contentType: string;
            fileSize?: number;
        };
        /** @description Request body for UploadMediaToChannel interaction */
        UploadMediaToChannelRequest: {
            payload?: {
                channelId: string;
                mediaUrl: string;
                fileName: string;
                contentType: string;
                fileSize?: number;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for DeleteMediaContent interaction */
        DeleteMediaContentPayload: {
            mediaContentId: string;
        };
        /** @description Request body for DeleteMediaContent interaction */
        DeleteMediaContentRequest: {
            payload?: {
                mediaContentId: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for GenerateImageFromUploadedImage interaction */
        GenerateImageFromUploadedImagePayload: {
            channelId: string;
            sourceMediaContentId: string;
            prompt: string;
        };
        /** @description Request body for GenerateImageFromUploadedImage interaction */
        GenerateImageFromUploadedImageRequest: {
            payload?: {
                channelId: string;
                sourceMediaContentId: string;
                prompt: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for GenerateVideoFromPrompt interaction */
        GenerateVideoFromPromptPayload: {
            channelId: string;
            prompt: string;
        };
        /** @description Request body for GenerateVideoFromPrompt interaction */
        GenerateVideoFromPromptRequest: {
            payload?: {
                channelId: string;
                prompt: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for RetryNanobanana2ImageGeneration interaction */
        RetryNanobanana2ImageGenerationPayload: {
            channelId: string;
        };
        /** @description Request body for RetryNanobanana2ImageGeneration interaction */
        RetryNanobanana2ImageGenerationRequest: {
            payload?: {
                channelId: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Payload for RetrySora2VideoGeneration interaction */
        RetrySora2VideoGenerationPayload: {
            channelId: string;
            sora2CallId: string;
        };
        /** @description Request body for RetrySora2VideoGeneration interaction */
        RetrySora2VideoGenerationRequest: {
            payload?: {
                channelId: string;
                sora2CallId: string;
            };
            /** @description Activity name for activity-based interactions */
            activity?: string | null;
            /** @description Activity instance ID */
            activityId?: string | null;
        };
        /** @description Parameters for register API */
        RegisterParams: {
            username?: string;
            email?: string;
            password?: string;
        };
        /** @description Response from register API */
        RegisterResponse: {
            [key: string]: unknown;
        };
        /** @description Parameters for login API */
        LoginParams: {
            identifier?: string;
            password?: string;
        };
        /** @description Response from login API */
        LoginResponse: {
            [key: string]: unknown;
        };
        /** @description Parameters for getUploadUrl API */
        GetUploadUrlParams: {
            fileName?: string;
            contentType?: string | null;
            expiresIn?: number | null;
        };
        /** @description Response from getUploadUrl API */
        GetUploadUrlResponse: {
            [key: string]: unknown;
        };
        /** @description Parameters for queryNanobanana2ImageGenerationStatus API */
        QueryNanobanana2ImageGenerationStatusParams: {
            apiCallId?: string;
        };
        /** @description Response from queryNanobanana2ImageGenerationStatus API */
        QueryNanobanana2ImageGenerationStatusResponse: {
            [key: string]: unknown;
        };
        /** @description Parameters for querySora2VideoGenerationStatus API */
        QuerySora2VideoGenerationStatusParams: {
            apiCallId?: string;
        };
        /** @description Response from querySora2VideoGenerationStatus API */
        QuerySora2VideoGenerationStatusResponse: {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ViewUserChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewUserChannelsRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ViewChannelFeedStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewChannelFeedStreamRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ViewChannelMediaContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewChannelMediaContentRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ViewChannelDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewChannelDetailsRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ViewNanobanana2ImageGenerationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewNanobanana2ImageGenerationStatusRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ViewSora2VideoGenerationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewSora2VideoGenerationStatusRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UpdateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChannelRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteChannelRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AddMediaToFeedStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMediaToFeedStreamRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RemoveMediaFromFeedStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveMediaFromFeedStreamRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ReorderFeedStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderFeedStreamRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UploadMediaToChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadMediaToChannelRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteMediaContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMediaContentRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GenerateImageFromUploadedImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageFromUploadedImageRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GenerateVideoFromPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateVideoFromPromptRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RetryNanobanana2ImageGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryNanobanana2ImageGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RetrySora2VideoGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrySora2VideoGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegisterParams"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginParams"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GetUploadUrlParams"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUploadUrlResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    queryNanobanana2ImageGenerationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["QueryNanobanana2ImageGenerationStatusParams"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryNanobanana2ImageGenerationStatusResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    querySora2VideoGenerationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["QuerySora2VideoGenerationStatusParams"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuerySora2VideoGenerationStatusResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
