import * as fs from 'fs';
import * as path from 'path';

const projectRoot = process.cwd();

/**
 * 扫描 backend 目录，获取所有模块文件
 * 排除 index.ts, *.template.ts, *.example.ts
 */
function getBackendModules(): string[] {
  const backendDir = path.join(projectRoot, 'backend');
  
  if (!fs.existsSync(backendDir)) {
    console.warn('backend directory not found');
    return [];
  }
  
  const files = fs.readdirSync(backendDir);
  
  return files
    .filter(file => 
      file.endsWith('.ts') && 
      file !== 'index.ts' && 
      !file.includes('.template.') && 
      !file.includes('.example.')
    )
    .map(file => file.replace('.ts', ''))
    .sort(); // 保持稳定的顺序
}

/**
 * 生成 backend/index.ts
 */
function generateBackendIndex() {
  const modules = getBackendModules();
  
  if (modules.length === 0) {
    // 生成空的导出
    const content = `// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-aggregates.ts

export const entities: any[] = []
export const relations: any[] = []
export const interactions: any[] = []
export const activities: any[] = []
export const dicts: any[] = []
`;
    fs.writeFileSync(path.join(projectRoot, 'backend/index.ts'), content);
    console.log('Generated empty backend/index.ts (no modules found)');
    return;
  }
  
  // 生成 import 语句
  const imports = modules.map(mod => 
    `import {
  entities as ${mod}Entities,
  relations as ${mod}Relations,
  interactions as ${mod}Interactions,
  activities as ${mod}Activities,
  dicts as ${mod}Dicts
} from './${mod}'`
  ).join('\n\n');
  
  // 生成 export 语句 - 每个数组单独一行，更易读
  const entitiesSpread = modules.map(m => `...${m}Entities`).join(', ');
  const relationsSpread = modules.map(m => `...${m}Relations`).join(', ');
  const interactionsSpread = modules.map(m => `...${m}Interactions`).join(', ');
  const activitiesSpread = modules.map(m => `...${m}Activities`).join(', ');
  const dictsSpread = modules.map(m => `...${m}Dicts`).join(', ');

  const exports = `
export const entities = [${entitiesSpread}]
export const relations = [${relationsSpread}]
export const interactions = [${interactionsSpread}]
export const activities = [${activitiesSpread}]
export const dicts = [${dictsSpread}]`;

  const content = `// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-aggregates.ts

${imports}

${exports}
`;

  fs.writeFileSync(path.join(projectRoot, 'backend/index.ts'), content);
  console.log(`Generated backend/index.ts with modules: ${modules.join(', ')}`);
}

// 主函数
function main() {
  console.log('=== Generating Backend Aggregates ===');
  console.log(`Project root: ${projectRoot}`);
  console.log('');
  
  generateBackendIndex();
  
  console.log('');
  console.log('Aggregate generation complete!');
}

main();

